### ISSUE TITLE
Error occurred in pagerank example

### ISSUE THREAD

**Issue by Ytinifni-zc** [thu-pacman/GridGraph#4]
Hi, an error occurred when I run the page rank example in using LiveJournal dataset.

```
./pagerank $DATASET_PATH/LiveJournal/LiveJournal_Grid 20 20
degree calculation used 0.30 seconds
pagerank: $GridGraph_path/core/bigvector.hpp:132: void BigVector<T>::lock(size_t, size_t) [with T = float; size_t = long unsigned int]: Assertion `lock_result==0' failed.
[1]    162003 abort (core dumped)  ./pagerank 
$DATSET_PATH/LiveJournal/LiveJournal_Grid 20 20
```

While others examples can be run normally.

**Comment by coolerzxw** [comment]
Hi. Running the program with sudo would solve the issue.

**Comment by Ytinifni-zc** [comment]
Thank you.
Does the function `mlock()` need root permission?

**Comment by coolerzxw** [comment]
Not always (as you can configure the size of memory every user can lock) but usually yes.
