### ISSUE TITLE
Trouble when partition graph

### ISSUE THREAD

**Issue by xiaogouaiyaotou** [thu-pacman/GridGraph#9]
Hello, I have trouble when I try to partition the graph. I used the input you provided as the test, the result is below:
![image](https://user-images.githubusercontent.com/47123798/64990921-6d2efa00-d896-11e9-80d0-a64057d47b0f.png)
And, I have trouble too when I run the "make" command as below:
![181568664797_ pic_hd](https://user-images.githubusercontent.com/47123798/64990973-8768d800-d896-11e9-98d9-7b5f0dac1136.jpg)
I solved this question by add `#include<function>` in /core/graph.hpp .  I suspect if this trouble caused by the incorrect solution of previous one. Do you have some ideas about this?

**Comment by coolerzxw** [comment]
Hi. I think you may check Issue #2 and see if those replies can help you.

**Comment by xiaogouaiyaotou** [comment]
Thank you. It actually worked. But in my machine, there still has some trouble when I use spmv to run it.
![image](https://user-images.githubusercontent.com/47123798/65457739-d91ede80-de11-11e9-9675-85135c89820c.png)

**Comment by coolerzxw** [comment]
SpMV assumes the graph is weighted. It seems that you were trying to run SpMV on an unweighted graph.

**Comment by xiaogouaiyaotou** [comment]
Ok, thank you very much. I think I can solve this problem now!
